import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Marquee from "@/components/Marquee";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const notoSerifBengali = Noto_Serif_Bengali({
    subsets: ["latin", "bengali"],
});

export const instant = false;

export const metadata: Metadata = {
    title: "BazarDor",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoSerifBengali.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        <Marquee />
        {children}
        <ToastContainer
          position="top-right"
          autoClose={3000}
          theme="colored"
        />
        <div>Footer</div>
      </body>
    </html>
  );
}